home:
   resource: "@AppBundle/Controller/HomeController.php"
   type: annotation

article:
   resource: "@AppBundle/Controller/Article/"
   type: annotation
   prefix: /article

movie:
   resource: "@AppBundle/Controller/Movie/"
   type: annotation
   prefix: /movie




