services:
#    app.example:
#        class: AppBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

 antispam:
    class: AppBundle\Antispam\Antispam
    arguments: ['%antispam_length%', '@mailer']


 string.util:
    class: AppBundle\Util\StringUtil
